name: PyPI Nightly Release

on:
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            cibw_arch: x86_64
          - runner: ubuntu-22.04-arm
            cibw_arch: aarch64
    runs-on: ["${{ matrix.runner }}"]
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Modify package name to etops-nightly
        run: |
          cd python
          sed -i 's/name = "etops"/name = "etops-nightly"/' pyproject.toml
          # Verify the change
          grep 'name = "etops-nightly"' pyproject.toml

      - name: Build wheels
        run: |
          export SETUPTOOLS_SCM_PRETEND_VERSION=$(python python/version_cli.py)
          echo "Building version: $SETUPTOOLS_SCM_PRETEND_VERSION"
          python -m cibuildwheel python --output-dir wheelhouse
        env:
          CIBW_CONTAINER_ENGINE: docker
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_arch }}
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ENVIRONMENT_PASS_LINUX: "SETUPTOOLS_SCM_PRETEND_VERSION"
          CIBW_BEFORE_ALL_LINUX: |
            apt update
            apt install -y git cmake make g++ libomp-dev

      - name: Test wheel import
        run: |
          cd python
          # Install the built wheel and test basic import
          python -m pip install wheelhouse/*.whl
          python -c "import etops; print('etops-nightly version:', etops.__version__)"

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.runner }}
          path: python/wheelhouse/*.whl

  publish:
    needs: build
    runs-on: ubuntu-latest # minimal trusted publishing job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist/
      - name: Check dists
        run: python -m pip install --upgrade twine && twine check dist/*
      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true